server:
  port: 9090

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/dh_bills
        registration:
          api-gateway:
            provider: keycloak-provider
            client-id: gateway-client
            client-secret: 51zNrXFTohJKlNlgCFOGHswtNChhoatb
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka