server:
  port: ${PORT:0}

spring:
  application:
    name: ms-users

ms-users:
  keycloak:
    serverUrl: http://localhost:8080
    realm: dh_bills
    clientId: users-client
    clientSecret: lSi2AcjSpQHrmgaEy7Ymz6RlQb3ijchf